/*====================================================================
    SISTEMA:      Sistema de Vendas / Projeto de Portfólio
    ARQUIVO:      05_DROPS_DIC.sql
    AUTOR:        Julio F. Zapolla
    DATA:         26/11/2025

    DESCRIÇÃO:
        Script responsável por remover (DROP) todas as tabelas,
        constraints e objetos relacionados para recriação completa
        do ambiente.
====================================================================*/

DROP TABLE DIC_BAIRRO CASCADE CONSTRAINTS 
;

DROP TABLE DIC_CATEGORIA CASCADE CONSTRAINTS 
;

DROP TABLE DIC_CIDADE CASCADE CONSTRAINTS 
;

DROP TABLE DIC_CLIENTE CASCADE CONSTRAINTS 
;

DROP TABLE DIC_DEPARTAMENTO CASCADE CONSTRAINTS 
;

DROP TABLE DIC_END_CLI CASCADE CONSTRAINTS 
;

DROP TABLE DIC_ESTADO CASCADE CONSTRAINTS 
;

DROP TABLE DIC_FUNCIONARIO CASCADE CONSTRAINTS 
;

DROP TABLE DIC_ITEM_PEDIDO CASCADE CONSTRAINTS 
;

DROP TABLE DIC_LOGRADOURO CASCADE CONSTRAINTS 
;

DROP TABLE DIC_PEDIDO CASCADE CONSTRAINTS 
;

DROP TABLE DIC_PRODUTO CASCADE CONSTRAINTS 
;

DROP TABLE DIC_DEPTO_UNIDADE CASCADE CONSTRAINTS 
;

DROP TABLE DIC_END_FUNCI CASCADE CONSTRAINTS 
;

DROP TABLE DIC_END_UNI CASCADE CONSTRAINTS 
;

DROP TABLE DIC_UNIDADE CASCADE CONSTRAINTS 
;

DROP TABLE DIC_HISTORICO_PRECO CASCADE CONSTRAINTS 
;

